
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSEOUT = 9;
  public static final int RBRAK = 4;
  public static final int DOUBLE = 35;
  public static final int LPAREN = 14;
  public static final int SEMI = 16;
  public static final int INT = 31;
  public static final int PRINTLN = 7;
  public static final int OUT = 8;
  public static final int MINUS = 26;
  public static final int CMP = 33;
  public static final int RPAREN = 15;
  public static final int FUN = 13;
  public static final int COMMA = 19;
  public static final int DIV = 28;
  public static final int PLUS = 25;
  public static final int ASSIGN = 30;
  public static final int IF = 22;
  public static final int DOT = 2;
  public static final int EOF = 0;
  public static final int TABLE = 5;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int MOD = 29;
  public static final int IMPORT = 10;
  public static final int EQU = 20;
  public static final int COLON = 21;
  public static final int LBRACE = 17;
  public static final int ELSE = 23;
  public static final int MAPVAR = 11;
  public static final int DOLLAR = 12;
  public static final int LBRAK = 3;
  public static final int RBRACE = 18;
  public static final int END = 24;
  public static final int STRING = 34;
  public static final int VAR = 32;
  public static final int PRINT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOT",
  "LBRAK",
  "RBRAK",
  "TABLE",
  "PRINT",
  "PRINTLN",
  "OUT",
  "CLOSEOUT",
  "IMPORT",
  "MAPVAR",
  "DOLLAR",
  "FUN",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "EQU",
  "COLON",
  "IF",
  "ELSE",
  "END",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "ASSIGN",
  "INT",
  "VAR",
  "CMP",
  "STRING",
  "DOUBLE"
  };
}

